const iconMappings = {
  "image/png": "icons/png-icon.png",
  "image/jpeg": "icons/jpeg-icon.png",
  "image/gif": "icons/gif-icon.png",
  "image/webp": "icons/webp-icon.png",
  "image/svg+xml": "icons/svg-icon.png",
  "image/x-icon": "icons/ico-icon.png",
  "image/icns": "icons/icns-icon.png",
  "application/pdf": "icons/pdf-icon.png",
  "application/msword": "icons/word-icon.png",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    "icons/word-icon.png",
  "application/vnd.ms-excel": "icons/excel-icon.png",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
    "icons/excel-icon.png",
  "application/vnd.ms-powerpoint": "icons/powerpoint-icon.png",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":
    "icons/powerpoint-icon.png",
  "text/plain": "icons/text-icon.png",
  "text/html": "icons/html-icon.png",
  "application/json": "icons/json-icon.png",
  "application/javascript": "icons/js-icon.png",
  "text/css": "icons/css-icon.png",
  "application/zip": "icons/zip-icon.png",
  "application/x-zip-compressed": "icons/zip-icon.png",
  "application/x-rar-compressed": "icons/rar-icon.png",
  "application/x-7z-compressed": "icons/7z-icon.png",
  "application/x-tar": "icons/tar-icon.png",
  "application/x-bzip2": "icons/bzip2-icon.png",
  "application/x-gzip": "icons/gzip-icon.png",
  "application/vnd.oasis.opendocument.text": "icons/odt-icon.png",
  "application/vnd.oasis.opendocument.spreadsheet": "icons/ods-icon.png",
  "application/vnd.oasis.opendocument.presentation": "icons/odp-icon.png",
  "audio/mpeg": "icons/mp3-icon.png",
  "audio/ogg": "icons/ogg-icon.png",
  "video/mp4": "icons/mp4-icon.png",
  "video/x-msvideo": "icons/avi-icon.png",
  "application/xml": "icons/xml-icon.png",
  "application/octet-stream": "icons/binary-icon.png",
  "application/x-msdownload": "icons/exe-icon.png",
  "application/x-apple-diskimage": "icons/dmg-icon.png",
  "application/x-debian-package": "icons/deb-icon.png",
  "application/x-rpm": "icons/rpm-icon.png",
  "application/x-msi": "icons/msi-icon.png",
  "application/x-sh": "icons/shell-icon.png",
  "application/x-csh": "icons/shell-icon.png",
  "application/x-executable": "icons/exe-icon.png",
  "text/csv": "icons/csv-icon.png",
  "application/x-java-archive": "icons/jar-icon.png",
  "application/x-python": "icons/python-icon.png",
  "application/x-c++": "icons/cpp-icon.png",
  "application/x-csharp": "icons/csharp-icon.png",
  "application/x-java-source": "icons/java-icon.png",
  "text/markdown": "icons/md-icon.png",
};

export default iconMappings;
